import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

const root = path.resolve(import.meta.dirname, "..");
const origin = "https://phantombladezerowiki.wiki";
const steam = "https://store.steampowered.com/app/4115450/Phantom_Blade_Zero/";
const ps = "https://www.playstation.com/en-us/games/phantom-blade-zero/";

const routes = [
  ["", "", ""],
  ["release-date/", "erscheinungsdatum/", "発売日/"],
  ["platforms/", "plattformen/", "対応機種/"],
  ["languages/", "sprachen/", "対応言語/"],
  ["combat-guide/", "kampf-guide/", "戦闘ガイド/"],
  ["beginners-guide/", "anfaenger-guide/", "初心者ガイド/"],
  ["questions/", "fragen/", "よくある質問/"],
  ["questions/is-phantom-blade-zero-on-ps5/", "fragen/phantom-blade-zero-ps5/", "よくある質問/ps5版はある/"],
  ["questions/is-phantom-blade-zero-on-pc/", "fragen/phantom-blade-zero-pc/", "よくある質問/pc版はある/"],
  ["questions/is-phantom-blade-zero-on-xbox/", "fragen/phantom-blade-zero-xbox/", "よくある質問/xbox版はある/"],
  ["questions/is-phantom-blade-zero-single-player/", "fragen/ist-es-einzelspieler/", "よくある質問/シングルプレイ専用/"],
  ["questions/is-phantom-blade-zero-open-world/", "fragen/ist-es-open-world/", "よくある質問/オープンワールド/"],
  ["platforms/pc-system-requirements/", "pc-systemanforderungen/", "pc動作環境/"],
];

const alternatesByEnglish = new Map(routes.map(([en, de, ja]) => [en, { en, de, ja }]));

function alternates({ en, de, ja }) {
  return `<link rel="alternate" hreflang="en" href="${origin}/${en}" /><link rel="alternate" hreflang="de" href="${origin}/de/${de}" /><link rel="alternate" hreflang="ja" href="${origin}/ja/${ja}" /><link rel="alternate" hreflang="x-default" href="${origin}/${en}" />`;
}

function breadcrumb(locale, route, title) {
  const baseName = locale === "de" ? "Startseite" : "ホーム";
  const items = [{ "@type": "ListItem", position: 1, name: baseName, item: `${origin}/${locale}/` }];
  if (route) items.push({ "@type": "ListItem", position: 2, name: title, item: `${origin}/${locale}/${route}` });
  return JSON.stringify({ "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: items });
}

function page(locale, data, routeMap) {
  const isDe = locale === "de";
  const base = routeMap[locale];
  const home = `${origin}/${locale}/`;
  const canonical = `${home}${base}`;
  const stylesheet = "../".repeat(base.split("/").filter(Boolean).length + 1) + "styles.css";
  const homeHref = "../".repeat(base.split("/").filter(Boolean).length);
  const nav = isDe
    ? [["erscheinungsdatum/", "Release"], ["plattformen/", "Plattformen"], ["kampf-guide/", "Kampf"], ["fragen/", "FAQ"]]
    : [["発売日/", "発売日"], ["対応機種/", "対応機種"], ["戦闘ガイド/", "戦闘"], ["よくある質問/", "FAQ"]];
  const navHtml = nav.map(([href, label]) => `<a href="${homeHref}${href}">${label}</a>`).join("");
  const sourceText = isDe ? "Primärquellen" : "一次情報";
  const footer = isDe ? "Inoffizieller Fan-Guide. Angaben werden mit offiziellen Quellen geprüft." : "非公式ファンガイド。公式情報を優先して確認しています。";
  const bc = `<script type="application/ld+json">${breadcrumb(locale, base, data.h1)}</script>`;
  return `<!doctype html><html lang="${locale}"><head><meta charset="utf-8" /><meta name="viewport" content="width=device-width, initial-scale=1" /><title>${data.title}</title><meta name="description" content="${data.description}" /><link rel="canonical" href="${canonical}" />${alternates(routeMap)}<link rel="stylesheet" href="${stylesheet}" />${bc}</head><body><header class="site-header"><a class="brand" href="${homeHref}"><span class="brand-mark">PBZ</span><span>Phantom Blade Zero Wiki</span></a><nav class="nav">${navHtml}</nav></header><main><section class="page-hero"><p class="eyebrow">${data.eyebrow}</p><h1>${data.h1}</h1><p>${data.lead}</p></section><section class="section content-grid"><article class="article-body">${data.body}<h2>${sourceText}</h2><p>${data.source}</p></article><aside class="toc"><h2>${isDe ? "Schnellnavigation" : "関連ページ"}</h2>${data.links.map(([href, label]) => `<a href="${homeHref}${href}">${label}</a>`).join("")}<a href="/${routeMap.en}">English</a></aside></section></main><footer class="footer"><p>${footer}</p><a href="${homeHref}">${isDe ? "Startseite" : "ホーム"}</a></footer></body></html>\n`;
}

const de = {
  "": { title:"Phantom Blade Zero Wiki Deutsch – Guides und Release", description:"Deutsches Phantom Blade Zero Wiki mit bestätigtem Release-Termin, Plattformen, Sprachen, Kampf-Grundlagen und vorsichtig geprüften Antworten.", eyebrow:"Deutscher Guide · Stand 18. Juli 2026", h1:"Phantom Blade Zero Wiki auf Deutsch", lead:"Aktuelle, quellenbasierte Informationen zu Release, PS5, PC, Sprachen, Kampfsystem und Story – ohne unbestätigte Mechaniken als Fakten auszugeben.", body:`<h2>Was bereits bestätigt ist</h2><p>Phantom Blade Zero erscheint nach aktuellem Stand am 29. Oktober 2026 für PlayStation 5; Steam zeigt wegen der globalen Freischaltung in manchen Regionen den 28. Oktober. Das Spiel ist ein Einzelspieler-Action-RPG von S-GAME und nutzt Unreal Engine 5.</p><h2>Spiel und Welt</h2><p>Im Mittelpunkt steht Soul, ein Assassine mit nur noch 66 Tagen zu leben. S-GAME beschreibt eine dunkle, halb offene Welt, die Wuxia, Kampfkunst, Maschinen und Okkultes zu „Kungfupunk“ verbindet. Mehr als 30 Waffen und über 20 Phantom Edges sind angekündigt.</p><h2>So nutzt du dieses Wiki</h2><p>Beginne mit Release und Plattformen. Kampfseiten trennen bestätigte Demo-Beobachtungen von Regeln, die erst in der Verkaufsversion getestet werden können. Seiten zu Bossen, Quests und Gegenständen werden erst indexiert, wenn konkrete Namen und Antworten vorliegen.</p>`, source:`Die Kerndaten stammen von der <a href="${steam}">offiziellen Steam-Seite</a> und der <a href="${ps}">PlayStation-Seite</a>.`, links:[["erscheinungsdatum/","Erscheinungsdatum"],["plattformen/","Plattformen"],["anfaenger-guide/","Anfänger-Guide"],["fragen/","Häufige Fragen"]]},
  "erscheinungsdatum/": { title:"Phantom Blade Zero Release – Datum und Uhrzeit", description:"Phantom Blade Zero erscheint am 29. Oktober 2026. Hier findest du Steam- und PS5-Datum, UTC-Zeit sowie Hinweise zu Preload und Editionen.", eyebrow:"Bestätigter Termin · geprüft am 18. Juli 2026", h1:"Wann erscheint Phantom Blade Zero?", lead:"Der offizielle PlayStation-Termin ist der 29. Oktober 2026 um 02:00 UTC. Steam kann abhängig von Zeitzone und Store-Region den 28. Oktober anzeigen.", body:`<h2>Bestätigter Release</h2><p>PlayStation nennt den 29. Oktober 2026 und 02:00 UTC. Steam führt aktuell den 28. Oktober 2026. Diese Anzeige ist mit einer weltweiten Freischaltung vereinbar, die in westlichen Zeitzonen noch auf den vorherigen Kalendertag fällt.</p><h2>Kein lokaler Mitternachts-Release bestätigt</h2><p>Aus dem Store-Datum folgt nicht automatisch, dass das Spiel überall um Mitternacht Ortszeit startet. Maßgeblich sind der regionale Countdown und eine mögliche offizielle Freischaltkarte von S-GAME.</p><h2>Noch offene Kaufdetails</h2><p>Preload-Zeit, Downloadgröße, Editionen, Preis, Vorbestellerboni und Review-Embargo sind nicht vollständig veröffentlicht. Diese Seite wird nur nach offiziellen Store- oder Publisher-Angaben aktualisiert.</p>`, source:`Verglichen wurden die aktuellen Einträge bei <a href="${ps}">PlayStation</a> und <a href="${steam}">Steam</a>.`, links:[["plattformen/","Plattformen"],["fragen/phantom-blade-zero-ps5/","PS5-Version"],["fragen/phantom-blade-zero-pc/","PC-Version"]]},
  "plattformen/": { title:"Phantom Blade Zero Plattformen – PS5, PC und Xbox", description:"Phantom Blade Zero ist für PS5 und Windows-PC bestätigt. Aktueller Status zu Xbox, PS4, Steam Deck, Controller und Plattformfunktionen.", eyebrow:"Plattformstatus · geprüft am 18. Juli 2026", h1:"Für welche Plattformen erscheint Phantom Blade Zero?", lead:"Bestätigt sind PlayStation 5 und Windows-PC über Steam. Eine Xbox-, PS4- oder Switch-Version wurde bislang nicht offiziell angekündigt.", body:`<h2>PlayStation 5</h2><p>Die offizielle PlayStation-Seite nennt eine PS5-Version für einen Spieler. DualSense-Vibration, Trigger-Effekte und Game Help werden unterstützt. Auflösung, Bildrate, Downloadgröße und mögliche Grafikmodi sind noch nicht vollständig beschrieben.</p><h2>Windows-PC</h2><p>Steam bestätigt Windows 10 oder 11 in 64 Bit, Singleplayer, Controller-Unterstützung und Family Sharing. Vollständige CPU-, GPU-, RAM- und Speicheranforderungen fehlen noch. Die Steam-Deck-Einstufung ist derzeit nicht abschließend.</p><h2>Nicht angekündigte Systeme</h2><p>Für Xbox Series X|S, Xbox One, PlayStation 4 und Nintendo Switch existiert aktuell keine offizielle Produktseite. „Nicht angekündigt“ bedeutet nicht dauerhaft ausgeschlossen, ist aber keine Bestätigung für eine spätere Version.</p>`, source:`Plattformdaten werden direkt mit <a href="${ps}">PlayStation</a> und <a href="${steam}">Steam</a> abgeglichen.`, links:[["fragen/phantom-blade-zero-ps5/","PS5"],["fragen/phantom-blade-zero-pc/","PC"],["fragen/phantom-blade-zero-xbox/","Xbox"],["pc-systemanforderungen/","PC-Anforderungen"]]},
  "sprachen/": { title:"Phantom Blade Zero Sprachen und deutsche Untertitel", description:"Phantom Blade Zero unterstützt 15 Sprachen. Deutsch ist für Benutzeroberfläche und Untertitel bestätigt, aber nicht als vollständige deutsche Sprachausgabe.", eyebrow:"Offizielle Steam-Sprachliste · 18. Juli 2026", h1:"Welche Sprachen unterstützt Phantom Blade Zero?", lead:"Steam listet 15 Sprachen. Englisch und vereinfachtes Chinesisch erhalten vollständige Sprachausgabe; Deutsch ist mit Oberfläche und Untertiteln bestätigt.", body:`<h2>Deutsch-Unterstützung</h2><p>Die deutsche Zeile auf Steam ist für Benutzeroberfläche und Untertitel markiert. Für vollständige deutsche Audioausgabe gibt es aktuell kein Häkchen. Eine deutschsprachige Store-Seite ist daher kein Nachweis für eine deutsche Synchronisation.</p><h2>Alle angekündigten Sprachen</h2><p>Unterstützt werden Englisch, vereinfachtes Chinesisch, Französisch, Deutsch, Spanisch aus Spanien, Russisch, Japanisch, traditionelles Chinesisch, brasilianisches Portugiesisch, Koreanisch, Italienisch, Thai, Vietnamesisch, Portugiesisch aus Portugal und lateinamerikanisches Spanisch.</p><h2>Was noch getestet werden muss</h2><p>Unklar ist, ob Audio und Text frei kombiniert werden können, ob Sprachpakete separat geladen werden und welche Untertiteloptionen verfügbar sind. Diese Punkte werden auf PS5 und PC nach Release geprüft.</p>`, source:`Die Aufteilung nach Oberfläche, Audio und Untertiteln stammt aus der <a href="${steam}">offiziellen Steam-Sprachtabelle</a>.`, links:[["fragen/","FAQ"],["plattformen/","Plattformen"],["erscheinungsdatum/","Release"]]},
  "kampf-guide/": { title:"Phantom Blade Zero Kampf-Guide – Blocken, Parieren, Ausweichen", description:"Deutscher Phantom Blade Zero Kampf-Guide zu Blocken, Parieren, Ausweichen, Waffen und Phantom Edges – bestätigte Fakten klar von Launch-Tests getrennt.", eyebrow:"Kampf-Grundlagen vor Release", h1:"Phantom Blade Zero Kampf-Guide", lead:"Der Kampf verbindet schnelles Wuxia-Tempo mit Blocken, Parieren, Ausweichen, vielen Waffen und kombinierbaren Phantom Edges.", body:`<h2>Bestätigte defensive Optionen</h2><p>Ein PlayStation-Hands-on beschrieb Blocken durch Halten von L1 sowie zeitlich abgestimmtes Parieren und Ausweichen. Erfolgreiche aktive Verteidigung konnte Gegenangriffe eröffnen. Exakte Zeitfenster, Ressourcen und universelle Konter sind für die Verkaufsversion noch nicht veröffentlicht.</p><h2>Waffen und Techniken</h2><p>Steam verspricht mehr als 30 Waffen und über 20 Phantom Edges. Mächtige Gegner können Waffen und deren charakteristische Techniken liefern. Welche Drops garantiert sind, wie Verbesserungen funktionieren und welche Kombinationen optimal sind, muss im fertigen Spiel getestet werden.</p><h2>Sicher lernen</h2><p>Beobachte zunächst eine vollständige Angriffsfolge mit Blocken. Teste anschließend Parieren und Ausweichen getrennt, ohne gleichzeitig Waffe und Distanz zu wechseln. So lässt sich erkennen, welche Entscheidung tatsächlich den Vorteil erzeugt.</p>`, source:`Kampfgrundlagen basieren auf offiziellen S-GAME-, Steam- und PlayStation-Angaben; Frame-Daten bleiben bis zum Launch unbestätigt.`, links:[["anfaenger-guide/","Anfänger-Guide"],["fragen/ist-es-einzelspieler/","Einzelspieler"],["fragen/ist-es-open-world/","Weltstruktur"]]},
  "anfaenger-guide/": { title:"Phantom Blade Zero Anfänger-Guide – Sicher starten", description:"Deutscher Anfänger-Guide für Phantom Blade Zero: Einstellungen, Blocken, Parieren, Ausweichen, Waffenvergleich und spoilerarmer Start.", eyebrow:"Spoilerarmer Einstieg", h1:"Phantom Blade Zero Anfänger-Guide", lead:"Richte zuerst Steuerung und Kamera ein, lerne danach defensive Entscheidungen und vergleiche Waffen anhand von Reichweite und Erholung statt nur Schaden.", body:`<h2>Die richtige Lernreihenfolge</h2><p>Prüfe Untertitel, Helligkeit, Kamera, Controller und Tastenbelegung. Nutze Blocken, um gegnerische Folgen zu beobachten. Übe danach jeweils nur einen Parier- oder Ausweichpunkt und greife erst an, wenn das Zeitfenster erkennbar ist.</p><h2>Nicht zu früh auf einen Build festlegen</h2><p>Mit mehr als 30 angekündigten Waffen und über 20 Phantom Edges lohnt sich frühes Experimentieren. Eine spektakuläre Technik ist nicht automatisch sicher. Vergleiche Reichweite, Erholungszeit, Position nach dem Angriff und den Nutzen in kurzen Boss-Fenstern.</p><h2>Vor Spoilern schützen</h2><p>Die öffentliche Ausgangslage nennt Soul, The Order und die Frist von 66 Tagen. Namen späterer Bosse, Regionen, Verräter und Endbedingungen gehören nicht in einen Anfängerweg. Detailseiten werden mit klaren Spoilerhinweisen versehen.</p>`, source:`Der Guide nutzt nur bestätigte Grundfunktionen; genaue Tutorials und Upgrade-Kosten werden nach Release ergänzt.`, links:[["kampf-guide/","Kampf-Guide"],["plattformen/","Plattformen"],["fragen/","FAQ"]]},
  "fragen/": { title:"Phantom Blade Zero FAQ Deutsch – Release, PS5, PC und Gameplay", description:"Deutsche Antworten zu Phantom Blade Zero: Release, PS5, PC, Xbox, Einzelspieler, halb offene Welt, Sprachen und Systemanforderungen.", eyebrow:"Bestätigte Antworten · Stand 18. Juli 2026", h1:"Phantom Blade Zero – Häufige Fragen", lead:"Direkte Antworten mit klarer Trennung zwischen bestätigten Store-Angaben und Funktionen, die erst zum Launch getestet werden können.", body:`<h2>Release und Plattformen</h2><p>Der PlayStation-Release ist für den 29. Oktober 2026 um 02:00 UTC angesetzt. Steam kann den 28. Oktober anzeigen. Bestätigt sind PS5 und Windows-PC; eine Xbox-, PS4- oder Switch-Version wurde nicht angekündigt.</p><h2>Spielmodus und Welt</h2><p>PlayStation führt das Spiel für einen Spieler. S-GAME bezeichnet die Struktur als halb offen: mehrere handgefertigte Karten statt einer einzigen nahtlosen Welt. Online-Koop, PvP und lokale Mehrspielerfunktionen sind nicht offiziell bestätigt.</p><h2>Sprachen und Technik</h2><p>Steam listet 15 Sprachen. Deutsch umfasst Oberfläche und Untertitel, nicht bestätigte Vollvertonung. Unreal Engine 5 ist bestätigt; vollständige PC-Hardwareanforderungen und konkrete Leistungsmodi stehen noch aus.</p>`, source:`Antworten werden anhand offizieller Store- und Entwicklerseiten aktualisiert und mit einem Prüfdatum versehen.`, links:[["fragen/phantom-blade-zero-ps5/","Ist es auf PS5?"],["fragen/phantom-blade-zero-pc/","Ist es auf PC?"],["fragen/phantom-blade-zero-xbox/","Ist es auf Xbox?"],["fragen/ist-es-einzelspieler/","Einzelspieler?"],["fragen/ist-es-open-world/","Open World?"]]},
  "fragen/phantom-blade-zero-ps5/": { title:"Kommt Phantom Blade Zero für PS5?", description:"Ja. Phantom Blade Zero erscheint offiziell am 29. Oktober 2026 für PS5 und unterstützt DualSense-Effekte sowie PlayStation Game Help.", eyebrow:"Direkte Antwort · geprüft 18. Juli 2026", h1:"Kommt Phantom Blade Zero für PS5?", lead:"Ja. PlayStation führt eine PS5-Version mit Veröffentlichung am 29. Oktober 2026 um 02:00 UTC.", body:`<h2>Offiziell bestätigte PS5-Funktionen</h2><p>Die Produktseite nennt einen Spieler, Vibration und Trigger-Effekte des DualSense-Controllers sowie Game Help. Damit sind Plattform und diese Funktionen bestätigt, nicht jedoch ein bestimmter Auflösungs- oder Bildratenmodus.</p><h2>Noch offene Details</h2><p>Downloadgröße, Preload, Preis, Editionen, Trophäenliste, 60-fps-Modus, Raytracing und möglicher PS5-Pro-Support sind noch nicht vollständig veröffentlicht. Solche Angaben werden erst nach offizieller Nennung oder Tests ergänzt.</p><h2>Release-Anzeige</h2><p>Der PS5-Termin ist der 29. Oktober. Steam kann aufgrund von Zeitzonen den 28. Oktober anzeigen; das ist kein Beleg für zwei getrennte Veröffentlichungstermine.</p>`, source:`Die Antwort stützt sich auf die <a href="${ps}">offizielle PlayStation-Produktseite</a>.`, links:[["erscheinungsdatum/","Release"],["plattformen/","Plattformen"],["fragen/phantom-blade-zero-pc/","PC-Version"]]},
  "fragen/phantom-blade-zero-pc/": { title:"Kommt Phantom Blade Zero für PC?", description:"Ja. Phantom Blade Zero erscheint über Steam für Windows-PC. Aktueller Stand zu Release, Windows-Version, Controller, Denuvo und Anforderungen.", eyebrow:"Direkte Antwort · geprüft 18. Juli 2026", h1:"Kommt Phantom Blade Zero für PC?", lead:"Ja. Eine offizielle Steam-Version für Windows-PC ist bestätigt und kann bereits auf die Wunschliste gesetzt werden.", body:`<h2>Bestätigte PC-Fakten</h2><p>Steam nennt Windows 10 oder 11 in 64 Bit, Einzelspieler, Family Sharing und Controller-Unterstützung. Die Store-Seite weist außerdem aktuell auf Denuvo als Drittanbieter-DRM hin. Diese Konfiguration kann sich bis oder nach Release ändern.</p><h2>Unvollständige Systemanforderungen</h2><p>Konkrete Prozessoren, Grafikkarten, Arbeitsspeicher, Speicherplatz und Leistungsziele wurden noch nicht vollständig eingetragen. Eine Betriebssystemzeile allein reicht nicht, um einen PC als geeignet zu bewerten.</p><h2>PC-Funktionen nach Launch</h2><p>Ultrawide, HDR, Upscaling, Frame Generation, unbegrenzte Bildrate, Shader-Kompilierung und Steam-Deck-Kompatibilität werden erst nach offiziellen Spezifikationen oder reproduzierbaren Tests bewertet.</p>`, source:`Aktueller Nachweis ist die <a href="${steam}">offizielle Steam-Produktseite</a>.`, links:[["pc-systemanforderungen/","Systemanforderungen"],["plattformen/","Plattformen"],["fragen/phantom-blade-zero-ps5/","PS5-Version"]]},
  "fragen/phantom-blade-zero-xbox/": { title:"Kommt Phantom Blade Zero für Xbox?", description:"Eine Xbox-Version von Phantom Blade Zero ist aktuell nicht offiziell angekündigt. Bestätigt sind PS5 und Windows-PC; Gerüchte sind keine Plattformbestätigung.", eyebrow:"Plattformstatus · geprüft 18. Juli 2026", h1:"Kommt Phantom Blade Zero für Xbox?", lead:"Aktuell ist keine Version für Xbox Series X|S oder Xbox One offiziell angekündigt.", body:`<h2>Was bestätigt ist</h2><p>Phantom Blade Zero besitzt offizielle Produktseiten für PlayStation 5 und Windows-PC über Steam. Eine entsprechende Xbox-Store-Seite oder S-GAME-Ankündigung liegt derzeit nicht vor.</p><h2>„Nicht angekündigt“ ist die korrekte Formulierung</h2><p>Das bedeutet weder „für immer ausgeschlossen“ noch „später bestätigt“. Aussagen über eine zeitlich begrenzte Exklusivität oder einen geplanten Xbox-Port benötigen eine klare Quelle des Entwicklers, Publishers oder Plattformbetreibers.</p><h2>Game Pass</h2><p>Ohne angekündigte Xbox- oder PC-Game-Pass-Version gibt es auch keine Grundlage für eine Day-one-Game-Pass-Zusage. Diese Seite wird aktualisiert, falls Microsoft oder S-GAME eine Version offiziell listet.</p>`, source:`Der Status wird gegen die offiziellen PlayStation-, Steam- und Publisher-Kanäle geprüft.`, links:[["plattformen/","Plattformen"],["fragen/phantom-blade-zero-ps5/","PS5"],["fragen/phantom-blade-zero-pc/","PC"]]},
  "fragen/ist-es-einzelspieler/": { title:"Ist Phantom Blade Zero ein Einzelspieler-Spiel?", description:"Ja. PlayStation und Steam führen Phantom Blade Zero als Singleplayer beziehungsweise für einen Spieler. Koop und PvP sind nicht bestätigt.", eyebrow:"Bestätigter Spielmodus · 18. Juli 2026", h1:"Ist Phantom Blade Zero Einzelspieler?", lead:"Ja. Die offiziellen Store-Seiten kennzeichnen Phantom Blade Zero als Einzelspieler-Titel beziehungsweise als Spiel für einen Spieler.", body:`<h2>Was die Store-Seiten sagen</h2><p>PlayStation nennt „1 Spieler“, Steam führt „Single-player“. Die Handlung folgt dem festen Protagonisten Soul und wird als Einzelspieler-Action-RPG präsentiert.</p><h2>Kein bestätigter Koop- oder PvP-Modus</h2><p>Die aktuellen Beschreibungen kündigen weder Online-Koop noch lokalen Koop oder kompetitives PvP an. Online-Interaktionen in Altersfreigabehinweisen sind keine Bestätigung eines spielbaren Mehrspielermodus.</p><h2>Was nach Release geprüft wird</h2><p>Asynchrone Funktionen, Bestenlisten, Nachrichten, Fotofreigabe oder andere Netzwerkfeatures könnten existieren, ohne den Kernmodus zu verändern. Solche Funktionen werden separat dokumentiert, wenn sie offiziell genannt oder im Spiel sichtbar sind.</p>`, source:`Die Antwort folgt den Funktionsangaben auf <a href="${ps}">PlayStation</a> und <a href="${steam}">Steam</a>.`, links:[["fragen/","FAQ"],["kampf-guide/","Kampf"],["fragen/ist-es-open-world/","Weltstruktur"]]},
  "fragen/ist-es-open-world/": { title:"Ist Phantom Blade Zero Open World?", description:"Phantom Blade Zero besitzt laut S-GAME eine halb offene Welt mit mehreren handgefertigten Karten, nicht eine einzige vollständig nahtlose Open World.", eyebrow:"Offizielle Weltbeschreibung", h1:"Ist Phantom Blade Zero ein Open-World-Spiel?", lead:"Nicht im klassischen Sinn. S-GAME beschreibt Phantom Blade Zero als „semi-open world“ mit mehreren handgefertigten Karten angemessener Größe.", body:`<h2>Was „halb offen“ bedeutet</h2><p>Der Entwickler bevorzugt mehrere sorgfältig gebaute Gebiete mit unterschiedlichen Aktivitäten gegenüber einer einzigen riesigen, durchgehend verbundenen Karte mit wiederverwendeten Inhalten. Das bestätigt mehr Freiheit als einen reinen linearen Korridor, aber keine vollständig nahtlose Welt.</p><h2>Noch unbekannte Details</h2><p>Regionengröße, Schnellreise, Ladeübergänge, Rückkehr in ältere Gebiete, Tag-Nacht-Systeme und Kartenfortschritt sind nicht vollständig erklärt. Trailerbilder reichen nicht, um diese Systeme sicher abzuleiten.</p><h2>SEO- und Guide-Regel</h2><p>Dieses Wiki nennt die Struktur „halb offen“ und erstellt erst dann einzelne Regionsseiten, wenn offizielle oder im Spiel bestätigte Namen, Wege, Bosse und Aktivitäten vorliegen.</p>`, source:`Die Formulierung stammt aus S-GAMEs offizieller Vorstellung des Spiels auf dem PlayStation Blog.`, links:[["fragen/","FAQ"],["anfaenger-guide/","Anfänger"],["kampf-guide/","Kampf"]]},
  "pc-systemanforderungen/": { title:"Phantom Blade Zero PC-Systemanforderungen", description:"Aktueller Stand der Phantom Blade Zero PC-Anforderungen: Windows 10/11 64 Bit bestätigt; CPU, GPU, RAM, Speicher und Leistungsziele noch offen.", eyebrow:"PC-Daten · geprüft 18. Juli 2026", h1:"Phantom Blade Zero PC-Systemanforderungen", lead:"Steam bestätigt derzeit nur Windows 10 oder 11 in 64 Bit. Die vollständigen Mindest- und empfohlenen Hardwarewerte sind noch nicht veröffentlicht.", body:`<h2>Aktuell bestätigte Anforderung</h2><p>Sowohl im Mindest- als auch im Empfehlungsabschnitt steht Windows 10/11 64 Bit. Konkrete CPU-, GPU-, RAM-, DirectX- und Speicherangaben fehlen. Deshalb lässt sich noch keine seriöse Hardwareempfehlung ableiten.</p><h2>Weitere PC-Angaben</h2><p>Steam listet vollständige Controller-Unterstützung und empfiehlt einen Controller. Denuvo wird derzeit als Drittanbieter-DRM genannt. Steam-Deck-Kompatibilität, Ultrawide, HDR, Upscaling, Frame Generation und Bildratenlimit sind noch nicht abschließend bestätigt.</p><h2>So wird später getestet</h2><p>Benchmarks müssen Patch, Auflösung, Grafikpreset, Upscaling-Modus, CPU, GPU und Treiberversion nennen. Mindestwerte werden nicht automatisch als 60-fps-Ziel interpretiert; offizielle Leistungsziele oder reproduzierbare Messungen sind erforderlich.</p>`, source:`Die Tabelle wird nur nach Änderungen auf der <a href="${steam}">offiziellen Steam-Seite</a> aktualisiert.`, links:[["fragen/phantom-blade-zero-pc/","PC-Version"],["plattformen/","Plattformen"],["kampf-guide/","Kampf"]]},
};

const ja = {
  "": { title:"Phantom Blade Zero 攻略Wiki 日本語版", description:"Phantom Blade Zeroの日本語攻略Wiki。発売日、PS5・PC対応、対応言語、戦闘、初心者向け情報を公式情報ベースで整理します。", eyebrow:"日本語ガイド · 2026年7月18日更新", h1:"Phantom Blade Zero 攻略Wiki", lead:"発売日、対応機種、言語、戦闘システム、物語について、確認済み情報と発売後の検証項目を分けて掲載します。", body:`<h2>現在確認できる基本情報</h2><p>Phantom Blade ZeroはS-GAMEが開発する一人用アクションRPGです。PlayStation 5版は2026年10月29日発売予定で、Steam版は時差の関係から10月28日と表示される地域があります。Unreal Engine 5の採用も公式に案内されています。</p><h2>世界観と主人公</h2><p>主人公Soulは、組織「The Order」の総帥殺害の罪を着せられ、残された66日間で陰謀の真相を追います。武侠、機械、オカルトを組み合わせた世界観は「Kungfupunk」と表現され、セミオープンワールド形式が採用されています。</p><h2>このWikiの方針</h2><p>公式ストア、S-GAME、PlayStationの情報を優先します。ボス名、武器性能、クエスト分岐、エンディング条件などは、正式名称と具体的な答えを確認できるまで検索用サイトマップへ追加しません。</p>`, source:`基本情報は<a href="${steam}">Steam公式ページ</a>と<a href="${ps}">PlayStation公式ページ</a>で確認しています。`, links:[["発売日/","発売日"],["対応機種/","対応機種"],["初心者ガイド/","初心者ガイド"],["よくある質問/","よくある質問"]]},
  "発売日/": { title:"Phantom Blade Zero 発売日・日本時間", description:"Phantom Blade Zeroの発売日は2026年10月29日。PlayStationのUTC時刻、Steamの日付差、予約・プリロードの未確定情報を解説。", eyebrow:"発売日確認 · 2026年7月18日", h1:"Phantom Blade Zeroの発売日はいつ？", lead:"PlayStation 5版は2026年10月29日02:00 UTC発売予定です。Steamでは地域と時差により10月28日と表示されます。", body:`<h2>公式に掲載された日時</h2><p>PlayStationの商品ページは2026年10月29日02:00 UTCを掲載しています。Steamは10月28日を表示していますが、世界同時解禁の場合、北米などでは同じ瞬間が前日の日付になるため、二つの別発売日を意味するとは限りません。</p><h2>日本時間について</h2><p>02:00 UTCを日本標準時へ換算すると11:00 JSTです。ただし、実際の日本ストアでの解禁は地域別設定が優先されます。購入前にはPS StoreまたはSteamのカウントダウンを確認してください。</p><h2>未発表の購入情報</h2><p>予約開始日、価格、各エディション、予約特典、プリロード日時、ダウンロード容量は完全には発表されていません。小売店の仮日付や噂では更新せず、公式ストアの変更を基準にします。</p>`, source:`日時は<a href="${ps}">PlayStation</a>と<a href="${steam}">Steam</a>の現行表示を比較しています。`, links:[["対応機種/","対応機種"],["よくある質問/ps5版はある/","PS5版"],["よくある質問/pc版はある/","PC版"]]},
  "対応機種/": { title:"Phantom Blade Zero 対応機種 – PS5・PC・Xbox", description:"Phantom Blade ZeroはPS5とWindows PCで発売予定。Xbox、PS4、Switch、Steam Deckの現時点の公式対応状況を整理。", eyebrow:"対応機種 · 2026年7月18日確認", h1:"Phantom Blade Zeroの対応機種", lead:"現在公式に確認できる対応機種はPlayStation 5とWindows PCです。Xbox、PS4、Nintendo Switch版は発表されていません。", body:`<h2>PlayStation 5</h2><p>PlayStation公式ページはPS5版、一人用、DualSenseの振動機能とトリガーエフェクト、ゲームヘルプ対応を掲載しています。解像度、フレームレート、容量、グラフィックモードはまだ完全には公開されていません。</p><h2>Windows PC</h2><p>SteamはWindows 10/11 64ビット、シングルプレイ、フルコントローラー対応、Family Sharingを掲載しています。CPU、GPU、メモリ、ストレージ容量などの具体的な動作環境は未完成です。</p><h2>未発表の機種</h2><p>Xbox Series X|S、Xbox One、PS4、Nintendo Switchの商品ページは現在確認できません。「未発表」は将来の可能性を否定しませんが、後日発売を約束する表現でもありません。</p>`, source:`対応状況は<a href="${ps}">PlayStation</a>と<a href="${steam}">Steam</a>の公式商品ページを基準にしています。`, links:[["よくある質問/ps5版はある/","PS5版"],["よくある質問/pc版はある/","PC版"],["よくある質問/xbox版はある/","Xbox版"],["pc動作環境/","PC動作環境"]]},
  "対応言語/": { title:"Phantom Blade Zero 日本語対応・音声・字幕", description:"Phantom Blade Zeroは日本語のインターフェースと字幕に対応予定。日本語音声は未確認。全15言語と英語・中国語音声を解説。", eyebrow:"Steam公式言語表 · 2026年7月18日", h1:"Phantom Blade Zeroは日本語に対応する？", lead:"はい。Steamは日本語のインターフェースと字幕を掲載しています。ただし、日本語フル音声のチェックは現在ありません。", body:`<h2>日本語対応の範囲</h2><p>Steamの日本語行はインターフェースと字幕にチェックがあります。フル音声欄にはチェックがないため、現時点で日本語吹き替えを確定情報として扱うことはできません。日本語のストアページやトレーラーだけでは吹き替えの証拠になりません。</p><h2>発表済みの15言語</h2><p>英語、簡体字中国語、フランス語、ドイツ語、スペイン語、ロシア語、日本語、繁体字中国語、ブラジルポルトガル語、韓国語、イタリア語、タイ語、ベトナム語、ポルトガル語、ラテンアメリカスペイン語です。フル音声は英語と簡体字中国語に表示されています。</p><h2>発売後の確認項目</h2><p>音声と表示言語を別々に選べるか、言語パックが別ダウンロードか、字幕サイズや背景、会話ログ、PS5とPCの設定差を確認します。</p>`, source:`対応範囲は<a href="${steam}">Steam公式の言語表</a>から転記しています。`, links:[["よくある質問/","FAQ"],["対応機種/","対応機種"],["発売日/","発売日"]]},
  "戦闘ガイド/": { title:"Phantom Blade Zero 戦闘ガイド – ガード・パリィ・回避", description:"Phantom Blade Zeroの戦闘ガイド。ガード、パリィ、回避、30種類以上の武器、Phantom Edgesを公式情報と発売後検証に分けて解説。", eyebrow:"発売前の戦闘基礎", h1:"Phantom Blade Zero 戦闘ガイド", lead:"高速な武侠アクションに、ガード、パリィ、回避、多数の武器、組み合わせ可能なPhantom Edgesが組み込まれています。", body:`<h2>確認済みの防御手段</h2><p>PlayStationの試遊記事では、L1長押しによるガード、タイミングを合わせるパリィ、回避が紹介されました。パリィや回避に成功すると強力な反撃へつなげられます。ただし、製品版の受付時間、無敵時間、リソース消費、全攻撃への対応可否は未確定です。</p><h2>武器と敵の技</h2><p>Steamは30種類以上の武器と20種類以上のPhantom Edgesを案内しています。強敵を倒すことで、その武器と特徴的な技を獲得できると説明されています。すべての敵が武器を落とすとは限らず、強化や重複の仕様も発売後の確認が必要です。</p><h2>安全な練習方法</h2><p>まず一つの敵の連続攻撃をガードで観察します。次にパリィと回避を別々の試行で確認し、同時に武器や距離を変えないようにします。成功後の位置と反撃時間まで記録すると再現性のある攻略になります。</p>`, source:`公式記事で確認できる防御手段だけを基礎とし、フレーム情報や万能な対処法は発売後に検証します。`, links:[["初心者ガイド/","初心者ガイド"],["よくある質問/シングルプレイ専用/","シングルプレイ"],["よくある質問/オープンワールド/","世界構造"]]},
  "初心者ガイド/": { title:"Phantom Blade Zero 初心者ガイド", description:"Phantom Blade Zero初心者向け攻略。設定、ガード、パリィ、回避、武器比較、ネタバレを避けた序盤の進め方を解説。", eyebrow:"ネタバレを抑えた入門", h1:"Phantom Blade Zero 初心者ガイド", lead:"最初にカメラと操作設定を整え、防御の選択を学んでから、攻撃力だけでなく隙と射程で武器を比較します。", body:`<h2>最初に確認する設定</h2><p>字幕、明るさ、カメラ速度、ロックオン、コントローラー、ボタン配置を確認します。未知の敵には最初から大技を狙わず、ガードで攻撃列を見てから、一つのパリィまたは回避ポイントを選んで練習します。</p><h2>序盤から武器を試す理由</h2><p>公式には30種類以上の武器と20種類以上のPhantom Edgesが予定されています。見た目の派手さや単発ダメージだけで決めず、射程、攻撃後の硬直、位置、短い反撃時間に間に合うかを比較してください。</p><h2>ネタバレの扱い</h2><p>公開済みの前提はSoul、The Order、66日間の期限です。後半の人物、ボス、地域、裏切り、エンディング条件は初心者ルートに混ぜません。必要なページには見出し前にネタバレ警告を表示します。</p>`, source:`発売前は確認済みの基礎だけを掲載し、チュートリアル名や強化コストは製品版で更新します。`, links:[["戦闘ガイド/","戦闘ガイド"],["対応機種/","対応機種"],["よくある質問/","FAQ"]]},
  "よくある質問/": { title:"Phantom Blade Zero よくある質問 – 発売日・PS5・PC", description:"Phantom Blade Zeroの日本語FAQ。発売日、PS5、PC、Xbox、シングルプレイ、セミオープンワールド、日本語対応、PC動作環境を回答。", eyebrow:"確認済みFAQ · 2026年7月18日", h1:"Phantom Blade Zero よくある質問", lead:"公式ストアで確認できる答えと、製品版で検証が必要な機能を明確に分けています。", body:`<h2>発売日と機種</h2><p>PS5版は2026年10月29日02:00 UTC発売予定です。Steamでは地域により10月28日と表示されます。公式対応はPS5とWindows PCで、Xbox、PS4、Switch版は発表されていません。</p><h2>プレイ人数と世界構造</h2><p>PlayStationは一人用、Steamはシングルプレイと掲載しています。S-GAMEは、一枚の巨大で連続したマップではなく、複数の手作りマップを持つセミオープンワールドと説明しています。</p><h2>日本語と技術情報</h2><p>日本語はインターフェースと字幕に対応予定ですが、日本語フル音声は現在未確認です。Unreal Engine 5を採用し、PCはWindows 10/11 64ビットが確認済みですが、CPUやGPUなどの完全な動作環境はまだ掲載されていません。</p>`, source:`回答は公式ストアと開発者発表を優先し、確認日を付けて更新します。`, links:[["よくある質問/ps5版はある/","PS5版は？"],["よくある質問/pc版はある/","PC版は？"],["よくある質問/xbox版はある/","Xbox版は？"],["よくある質問/シングルプレイ専用/","一人用？"],["よくある質問/オープンワールド/","オープンワールド？"]]},
  "よくある質問/ps5版はある/": { title:"Phantom Blade ZeroはPS5で発売される？", description:"はい。Phantom Blade Zero PS5版は2026年10月29日発売予定。DualSense機能、ゲームヘルプ、未発表の性能モードを整理。", eyebrow:"回答 · 2026年7月18日確認", h1:"Phantom Blade ZeroはPS5で発売される？", lead:"はい。PlayStation公式ページにPS5版と2026年10月29日02:00 UTCの発売予定が掲載されています。", body:`<h2>確認済みのPS5機能</h2><p>一人用、DualSenseワイヤレスコントローラーの振動機能とトリガーエフェクト、ゲームヘルプ対応が明記されています。PS5版の存在だけでなく、これらの機能は公式ストア情報として確認できます。</p><h2>まだ確認できない項目</h2><p>ダウンロード容量、プリロード、価格、エディション、トロフィー、60fpsモード、レイトレーシング、PS5 Pro向け機能は完全には発表されていません。映像から解像度やフレームレートを断定しません。</p><h2>Steamとの日付差</h2><p>Steamが10月28日と表示する地域がありますが、時差による同一解禁時刻の可能性があります。二つの別発売日として扱わず、地域ストアのカウントダウンを優先します。</p>`, source:`根拠は<a href="${ps}">PlayStation公式商品ページ</a>です。`, links:[["発売日/","発売日"],["対応機種/","対応機種"],["よくある質問/pc版はある/","PC版"]]},
  "よくある質問/pc版はある/": { title:"Phantom Blade ZeroはPCで発売される？", description:"はい。Phantom Blade ZeroはSteamでWindows PC版を発売予定。Windows、コントローラー、Denuvo、動作環境の現状を解説。", eyebrow:"回答 · 2026年7月18日確認", h1:"Phantom Blade ZeroはPCで発売される？", lead:"はい。Windows PC向けのSteam公式ページが公開され、ウィッシュリストへ追加できます。", body:`<h2>現在確認できるPC情報</h2><p>SteamはWindows 10/11 64ビット、シングルプレイ、Family Sharing、フルコントローラー対応を掲載しています。また、現時点ではDenuvoをサードパーティーDRMとして表示しています。発売までに表示が変更される可能性があります。</p><h2>完全な動作環境は未発表</h2><p>CPU、GPU、メモリ、ストレージ容量、DirectX、最低・推奨の目標フレームレートはまだ記入されていません。OSだけを見て、自分のPCで快適に動くと判断することはできません。</p><h2>発売後に確認する機能</h2><p>ウルトラワイド、HDR、アップスケーリング、フレーム生成、上限なしフレームレート、シェーダー処理、Steam Deck互換性を、公式仕様または再現可能なテストで確認します。</p>`, source:`現行情報は<a href="${steam}">Steam公式商品ページ</a>に基づきます。`, links:[["pc動作環境/","PC動作環境"],["対応機種/","対応機種"],["よくある質問/ps5版はある/","PS5版"]]},
  "よくある質問/xbox版はある/": { title:"Phantom Blade ZeroはXboxで発売される？", description:"Phantom Blade ZeroのXbox Series X|S版は現在未発表。確認済みのPS5・PC版と、Game Passを含む未確認情報を整理。", eyebrow:"機種状況 · 2026年7月18日確認", h1:"Phantom Blade ZeroはXboxで発売される？", lead:"現在、Xbox Series X|SおよびXbox One版は公式に発表されていません。", body:`<h2>公式に確認できる機種</h2><p>PlayStation 5とWindows PCには公式の商品ページがあります。一方、Xbox Storeの商品ページやS-GAMEによるXbox版の発表は現在確認できません。</p><h2>「未発表」と「発売されない」は別</h2><p>未発表は、永久に発売されないという意味ではありません。しかし、時限独占や後発移植が決まったという意味でもありません。機種追加にはS-GAME、パブリッシャー、Microsoftの明確な発表が必要です。</p><h2>Game Passについて</h2><p>Xbox版やPC Game Pass版が発表されていないため、発売日からGame Passへ入るという情報も確認できません。公式ストアに変更があればこのページを更新します。</p>`, source:`PlayStation、Steam、S-GAMEの公式チャンネルを比較して判断しています。`, links:[["対応機種/","対応機種"],["よくある質問/ps5版はある/","PS5"],["よくある質問/pc版はある/","PC"]]},
  "よくある質問/シングルプレイ専用/": { title:"Phantom Blade Zeroはシングルプレイ専用？", description:"公式ストアはPhantom Blade Zeroを一人用・シングルプレイと掲載。協力プレイ、PvP、オンライン機能の確認状況を解説。", eyebrow:"プレイ人数 · 2026年7月18日", h1:"Phantom Blade Zeroはシングルプレイ？", lead:"はい。PlayStationは一人用、Steamはシングルプレイとして掲載しています。", body:`<h2>公式ストアの表示</h2><p>PlayStationの商品ページは「1 player」、Steamの機能一覧は「Single-player」と表示しています。物語は固定主人公Soulを追う一人用アクションRPGとして紹介されています。</p><h2>協力プレイとPvP</h2><p>オンライン協力、ローカル協力、対戦PvPは現在発表されていません。年齢区分にオンラインインタラクションの注意があっても、プレイ可能なマルチプレイヤーモードの証明にはなりません。</p><h2>発売後の確認</h2><p>ランキング、非同期メッセージ、写真共有などのネットワーク機能が追加される可能性はあります。それらが存在しても、中心がシングルプレイであることとは矛盾しないため、別項目として記録します。</p>`, source:`<a href="${ps}">PlayStation</a>と<a href="${steam}">Steam</a>の機能欄を根拠にしています。`, links:[["よくある質問/","FAQ"],["戦闘ガイド/","戦闘"],["よくある質問/オープンワールド/","世界構造"]]},
  "よくある質問/オープンワールド/": { title:"Phantom Blade Zeroはオープンワールド？", description:"Phantom Blade Zeroは完全な一枚マップではなく、複数の手作りマップで構成されるセミオープンワールドとS-GAMEが説明。", eyebrow:"公式の世界構造", h1:"Phantom Blade Zeroはオープンワールド？", lead:"一般的な完全オープンワールドとは異なります。S-GAMEは複数の手作りマップを持つセミオープンワールドと説明しています。", body:`<h2>セミオープンワールドの意味</h2><p>開発者は、再利用された要素で埋めた一枚の巨大な連続世界ではなく、適切な規模で多様な活動を配置した複数マップを作る方針を説明しています。一本道より探索性がありますが、完全にシームレスとは限りません。</p><h2>未発表の仕様</h2><p>各地域の広さ、ロードの境界、ファストトラベル、過去地域への戻り方、昼夜、マップ達成率は完全には公開されていません。トレーラーの場面だけで移動ルールを断定しません。</p><h2>攻略ページの追加基準</h2><p>地域名、ルート、ボス、活動が公式または製品版で確認できた時点で個別ページを作ります。発売前の仮名だけで大量の地域ページをインデックスさせません。</p>`, source:`S-GAMEがPlayStation Blogで説明した「semi-open world」を基準にしています。`, links:[["よくある質問/","FAQ"],["初心者ガイド/","初心者"],["戦闘ガイド/","戦闘"]]},
  "pc動作環境/": { title:"Phantom Blade Zero PC動作環境・推奨スペック", description:"Phantom Blade ZeroのPC動作環境。Windows 10/11 64ビットは確認済み、CPU・GPU・メモリ・容量はまだ未発表です。", eyebrow:"PC仕様 · 2026年7月18日確認", h1:"Phantom Blade Zero PC動作環境", lead:"Steamで現在確認できる要件はWindows 10/11 64ビットだけです。最低・推奨ハードウェアの完全な数値は未発表です。", body:`<h2>現在掲載されている要件</h2><p>最低要件と推奨要件の両方にWindows 10/11 64 Bitと記載されています。具体的なCPU、GPU、メモリ、DirectX、空き容量がないため、現時点で特定のグラフィックボードを推奨することはできません。</p><h2>そのほかのPC情報</h2><p>Steamはフルコントローラー対応を表示し、開発者はコントローラーでのプレイを推奨しています。Denuvoも現在掲載されています。Steam Deck、ウルトラワイド、HDR、アップスケーリング、フレーム生成は最終確認前です。</p><h2>ベンチマークの掲載基準</h2><p>発売後の性能結果には、パッチ、解像度、プリセット、アップスケーリング、CPU、GPU、ドライバーを明記します。最低要件を自動的に60fpsの基準として扱わず、公式目標または再現可能な測定を使います。</p>`, source:`数値は<a href="${steam}">Steam公式のシステム要件</a>が更新された場合にのみ変更します。`, links:[["よくある質問/pc版はある/","PC版"],["対応機種/","対応機種"],["戦闘ガイド/","戦闘"]]},
};

for (const [enRoute, deRoute, jaRoute] of routes) {
  for (const [locale, route, content] of [["de", deRoute, de[deRoute]], ["ja", jaRoute, ja[jaRoute]]]) {
    if (!content) throw new Error(`Missing ${locale} content for ${route}`);
    const directory = path.join(root, locale, route);
    await mkdir(directory, { recursive: true });
    await writeFile(path.join(directory, "index.html"), page(locale, content, { en: enRoute, de: deRoute, ja: jaRoute }));
  }
}

const deAdditions = {
  "fragen/ist-es-einzelspieler/": "Auch eine Internetverbindungspflicht oder optionale Community-Funktion darf nicht mit Koop verwechselt werden. Der konkrete Netzwerkbedarf wird für Disc- und Downloadversion getrennt geprüft.",
  "fragen/ist-es-open-world/": "Nach Veröffentlichung wird außerdem dokumentiert, ob Entscheidungen oder Werkzeuge neue Wege öffnen und welche Gebiete nach Storyfortschritt weiterhin erreichbar bleiben.",
  "fragen/phantom-blade-zero-pc/": "Die Prüfung berücksichtigt außerdem Tastatur-und-Maus-Bedienung, freie Tastenbelegung, Controller-Symbole und die Möglichkeit, Audio- und Textsprache getrennt einzustellen.",
  "fragen/phantom-blade-zero-ps5/": "Zum Launch werden auch Barrierefreiheit, Controller-Belegung, Untertiteloptionen und Unterschiede zwischen Performance- und Qualitätsmodus mit Versionsnummer dokumentiert.",
  "fragen/phantom-blade-zero-xbox/": "Suchergebnisse und Händlerseiten ohne offiziellen Produkteintrag werden deshalb nicht als Beleg für eine Xbox-Veröffentlichung oder ein konkretes Zeitfenster verwendet.",
  "pc-systemanforderungen/": "Sobald vollständige Werte erscheinen, werden Mindest- und Empfehlungsstufe getrennt erklärt und nicht zu einer einzigen vermeintlichen Zielkonfiguration vermischt.",
  "plattformen/": "Regionale Store-Anzeigen können voneinander abweichen. Eine Plattform gilt erst dann als bestätigt, wenn ein offizieller Produkteintrag oder eine eindeutige Publisher-Mitteilung vorliegt.",
};

for (const [route, text] of Object.entries(deAdditions)) {
  const file = path.join(root, "de", route, "index.html");
  let html = await readFile(file, "utf8");
  if (!html.includes(text)) html = html.replace("<h2>Primärquellen</h2>", `<p>${text}</p><h2>Primärquellen</h2>`);
  await writeFile(file, html);
}

for (const [enRoute, deRoute, jaRoute] of routes) {
  const englishFile = path.join(root, enRoute, "index.html");
  let html = await readFile(englishFile, "utf8");
  if (!html.includes('hreflang="de"')) html = html.replace("</head>", `${alternates({ en: enRoute, de: deRoute, ja: jaRoute })}</head>`);
  await writeFile(englishFile, html);
}

console.log(`Added ${routes.length * 2} localized pages with reciprocal en/de/ja hreflang.`);
