import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

const root = path.resolve(import.meta.dirname, "..");
const officialSteam = "https://store.steampowered.com/app/4115450/Phantom_Blade_Zero/";
const officialBlog = "https://blog.playstation.com/2023/05/24/phantom-blade-zero-a-new-beginning-in-a-long-journey/";
const handsOn = "https://blog.playstation.com/2024/06/12/a-closer-look-at-11-ps5-titles-from-summer-game-fest-2024/";

const additions = {
  "beginners-guide/index.html": `<h2>What Is Confirmed Before Launch</h2><p>PlayStation's 2024 hands-on report says holding L1 blocks incoming attacks, while timed parries or dodges can create powerful counterattacks. The official Steam page also confirms more than 30 weapons and more than 20 Phantom Edges, so the opening hours should be used to test several options rather than forcing one assumed build. Exact tutorial order, upgrade costs, healing rules, checkpoints, and difficulty settings still require release-version testing.</p><h2>A Safe First-Lesson Order</h2><ol><li>Adjust camera, subtitles, brightness, and controls.</li><li>Use blocking to observe a full enemy string.</li><li>Practice one deliberate parry or dodge response at a time.</li><li>Compare weapon recovery before comparing raw damage.</li><li>Spend special resources only after recognizing a real opening.</li></ol>`,
  "combat-guide/index.html": `<h2>Confirmed Combat Baseline</h2><p>A PlayStation hands-on preview describes three defensive choices: hold L1 to block, time a parry, or dodge for a counterattack opportunity. S-GAME has separately framed the game as fast action inspired by wuxia and 1990s kungfu cinema, with complex-looking move chains designed to require less button mashing than classic character-action games. That confirms the broad decision layer, but not final frame data, resource costs, invulnerability windows, or universal counters.</p><h2>How to Use This Guide at Launch</h2><p>Begin with the <a href="../combat/block-guide/">block guide</a>, then compare the <a href="../combat/parry-guide/">parry</a> and <a href="../combat/dodge-guide/">dodge</a> pages. Boss-specific pages will only prescribe a response after the release build has been tested.</p>`,
  "combat/advanced-combat/index.html": `<h2>Verified Foundation</h2><p>Official material confirms a large arsenal, enemy weapon acquisition, signature techniques, and mix-and-match Phantom Edges. That makes weapon switching and loadout planning legitimate advanced topics, but it does not yet prove animation canceling, combo scaling, hidden invulnerability, or exact meter loops. Those claims will stay out of this guide until they can be reproduced in the release build.</p><h2>Testing Standard</h2><p>Each advanced technique should record the platform, patch, input sequence, starting resource state, weapon, target, and repeatable result. Video evidence and a simpler beginner alternative will be added where possible, so a flashy route is never presented as the only viable answer.</p>`,
  "combat/block-guide/index.html": `<h2>What the Hands-On Preview Confirms</h2><p>PlayStation's Summer Game Fest 2024 report states that players could hold L1 to block incoming attacks in the demonstrated PS5 build. It also distinguished blocking from timed parries and dodges, which could lead to stronger counters. That is useful evidence for the core control, but it is not enough to claim that every launch enemy, unblockable attack, difficulty, or weapon follows identical rules.</p><h2>Beginner Drill</h2><p>Against a familiar early enemy, hold block and watch the complete string before attacking. Then repeat while noting chip damage, guard cost, pushback, and recovery. Only replace the block with a parry after the rhythm is recognizable.</p>`,
  "combat/brutal-moves/index.html": `<h2>Current Verification Status</h2><p>“Brutal Move” appears in public demo-era discussion, but a final official glossary, input, cue system, and counter table has not been published. This page therefore does not prescribe a universal response. At launch, the term will be checked against tutorials and accessibility menus before any timing advice is indexed as fact.</p><h2>Evidence Required for a Counter</h2><p>A useful entry must identify the enemy, visible or audible cue, attack sequence, defensive choices tested, successful response, punish window, and game version. If terminology differs between the demo and retail build, the release name will become primary and the old wording will remain only as an alias.</p>`,
  "combat/defense-guide/index.html": `<h2>Confirmed vs. Unconfirmed</h2><p>The confirmed layer is simple: the 2024 PlayStation hands-on build allowed blocking, parrying, and dodging, and successful active defense could create counterattack opportunities. Exact guard durability, chip damage, parry windows, dodge invulnerability, difficulty modifiers, and attack-color rules are not yet confirmed for the retail build. The guide will keep those two layers separate.</p><h2>Practical Training Loop</h2><p>Choose one early enemy, observe without attacking, block the sequence, then test parry and dodge on separate attempts. Record which choice leaves Soul close enough to punish. This controlled comparison is more reliable than repeatedly changing weapons, timing, and distance at once.</p>`,
  "combat/dodge-guide/index.html": `<h2>Public Evidence</h2><p>A PlayStation hands-on preview explicitly lists dodging alongside blocking and parrying and says a dodge can set up a devastating counterattack. It does not publish invulnerability frames, stamina cost, distance values, or a guarantee that every attack can be dodged in the same way. Those values remain launch-test items.</p><h2>First Tests to Run</h2><p>Test neutral and directional dodges at close and medium range against one repeatable attack. Note whether the success comes from invulnerability, moving outside the hitbox, or both. Then check recovery and camera position before recommending a punish. Boss guides will link here only after a response is repeatable.</p>`,
  "combat/ghoststep/index.html": `<h2>Why This Page Is Cautious</h2><p>Ghoststep has appeared as a community search term around showcased combat, but current official store descriptions do not provide a complete retail mechanic definition. Treating it as a universal dodge, teleport, parry, or resource move would therefore be premature. The release tutorial and control glossary will decide the final label and explanation.</p><h2>Launch Documentation Plan</h2><p>The first update will capture the exact name, input, unlock point, resource interaction, recovery, and valid enemy cues. Tests will distinguish avoiding a hit through movement from any true invulnerability window. If Ghoststep is renamed or absent in the release build, this URL will explain the terminology change instead of preserving inaccurate advice.</p>`,
  "combat/killer-moves/index.html": `<h2>Verification Boundary</h2><p>“Killer Move” is a high-interest demo-era term, but the final game's official public listings do not yet define its cue, input, or defensive rule. No single block, parry, dodge, or Ghoststep answer should be assumed across all enemies. Retail tutorials and accessibility settings will be the primary evidence.</p><h2>Boss-Guide Standard</h2><p>After launch, every listed Killer Move must include a plain-language tell, the safest tested response, an alternative for slower reactions, the resulting punish window, and the patch used. Failed responses will also be recorded when useful, because explaining why an intuitive block or early dodge fails is often more valuable than naming a button.</p>`,
  "combat/parry-guide/index.html": `<h2>What Is Publicly Confirmed</h2><p>PlayStation's 2024 hands-on report says the demonstrated build let players parry attacks and use the result for powerful counters. It also says holding L1 could block, giving beginners a lower-commitment way to study combat. The preview does not establish final parry frames, input buffering, weapon differences, or whether every enemy attack is parryable.</p><h2>Reliable Practice Method</h2><p>Start by blocking one complete attack string. Listen for rhythm and watch the attacker's shoulder or weapon rather than only the impact flash. On the next attempt, parry a single chosen strike. Once repeatable, record the resulting position and punish before testing another enemy or changing equipment.</p>`,
  "combat/resource-management/index.html": `<h2>Known Arsenal Context</h2><p>The official Steam description confirms more than 30 weapons, more than 20 Phantom Edges, and the ability to obtain weapons plus signature techniques from powerful foes. It does not yet publish the final meters, costs, regeneration rules, healing economy, or checkpoint resets. Resource advice must therefore remain principle-based until launch.</p><h2>Launch Measurement Sheet</h2><p>For every meter, record how it is gained, what spends it, the maximum capacity, whether upgrades alter it, and what persists after death or rest. Boss recommendations should reserve scarce options for verified openings and state the expected benefit. If a resource is unlimited between attempts, the guide will say so instead of implying scarcity.</p>`,
  "combat/sha-chi/index.html": `<h2>Status Before Release</h2><p>Sha-Chi is a commonly searched combat term, but the current PlayStation and Steam store descriptions do not publish a complete definition of its retail gain, spend, cap, or recovery rules. This guide will not reverse-engineer a final system from edited footage or an older demo alone.</p><h2>How the Retail Guide Will Be Built</h2><p>At launch, the tutorial wording will be quoted in short form and tested against normal attacks, defense, weapon techniques, and Phantom Edges. The page will show the HUD location, input, exact costs, refill conditions, upgrades, and a beginner budgeting rule. Any difference between PS5 and PC controls will be labeled rather than merged.</p>`,
  "comparisons/index.html": `<h2>Comparison Rules</h2><p>These pages compare confirmed design direction, not marketing vibes. S-GAME describes a fast wuxia action game with a semi-open world, more than 30 weapons, more than 20 Phantom Edges, and simplified execution for elaborate move chains. A PlayStation hands-on preview places it between character-action games and Soulslikes, but that observation does not prove shared progression, checkpoint, death, posture, or difficulty systems.</p><h2>Choose a Comparison</h2><p>Use the <a href="./phantom-blade-zero-vs-sekiro/">Sekiro comparison</a> for defensive timing, the <a href="./phantom-blade-zero-vs-ninja-gaiden/">Ninja Gaiden comparison</a> for high-speed action, or the <a href="./phantom-blade-zero-vs-soulslike-games/">Soulslike comparison</a> for genre labeling. Final verdicts follow retail testing.</p>`,
  "comparisons/phantom-blade-zero-vs-ninja-gaiden/index.html": `<h2>Confirmed Design Difference</h2><p>S-GAME founder Soulframe Liang cited Ninja Gaiden and Devil May Cry as exhilarating hack-and-slash references, then explained that Phantom Blade Zero aims to deliver complex-looking kungfu chains with less button mashing. This is an inspiration statement, not proof of identical combo trees, mission structure, ranking systems, or difficulty.</p><h2>Best Fit Today</h2><p>Players drawn to speed, weapon variety, precise defense, and cinematic martial-arts choreography have a reasonable basis for interest. Players specifically seeking Ninja Gaiden's exact movement tech, scoring, enemy density, or upgrade economy should wait for launch testing. The comparison will add side-by-side control and progression tables only after both claims and terminology can be verified.</p>`,
  "comparisons/phantom-blade-zero-vs-sekiro/index.html": `<h2>Confirmed Evidence</h2><p>A PlayStation hands-on writer said Phantom Blade Zero walks a line between character-action titles and Soulslikes and confirmed that the demo supported block, parry, and dodge choices. S-GAME, however, emphasizes fast wuxia choreography, simplified execution of elaborate chains, a semi-open world, and a broad weapon plus Phantom Edge arsenal.</p><h2>Bottom Line Before Launch</h2><p>Expect a meaningful overlap in reading enemy attacks and learning bosses, but do not expect Sekiro's posture, resurrection, prosthetic, checkpoint, or progression systems unless retail evidence confirms an equivalent. Phantom Blade Zero may reward defensive timing while still building a different combat identity around weapon acquisition and cinematic kungfu. This page will be retested on both PS5 and PC after release.</p>`,
  "guides/beginner-mistakes/index.html": `<h2>Pre-Launch Mistake to Avoid</h2><p>The biggest information mistake is treating showcase footage as a complete rules manual. Official material confirms block, parry, dodge, 30-plus weapons, 20-plus Phantom Edges, and enemy weapon acquisition, but final timing windows and progression details remain unknown. Use those confirmed facts to plan experiments, not to lock in a build before release.</p><h2>Recovery Rule</h2><p>When an approach fails, change only one variable: defense choice, distance, weapon, or timing. That makes the result teachable. Changing the full loadout after every loss makes it difficult to identify whether the problem was recognition, execution, positioning, or an unsuitable punish.</p>`,
  "guides/boss-prep/index.html": `<h2>Evidence-Based Preparation</h2><p>Official previews establish that blocking can be used to read attacks and that parries or dodges can produce counters. They do not establish one defensive answer for every boss. Begin each fight with observation, then test responses separately and keep a fast, low-commitment punish available while learning.</p><h2>What to Record</h2><p>Note the patch, difficulty, weapon, Phantom Edges, phase trigger, attack cue, successful response, and reward. Separate a safe clear strategy from a speed-kill route. After launch, each boss checklist will link to verified acquisition and upgrade pages so preparation advice can be reproduced instead of depending on unexplained gear.</p>`,
  "guides/first-five-hours/index.html": `<h2>Why Experiment Early</h2><p>The official Steam listing promises more than 30 weapons and over 20 Phantom Edges, while S-GAME says powerful enemies can yield their weapons and signature techniques. The first hours should therefore teach comparison: recovery, reach, defensive comfort, and how a tool fits a real opening. A visually dramatic option is not automatically the safest beginner choice.</p><h2>Information Hygiene</h2><p>Use only pages labeled spoiler-free until the game introduces a character, faction, or region. Record tutorial names exactly, because fan terminology from demos may not match the retail localization. If a guide conflicts with the current patch or menu, prefer the game and report the discrepancy for correction.</p>`,
  "guides/index.html": `<h2>Verified Guide Layers</h2><p>Before release, this hub separates confirmed store and developer facts from mechanics that still need hands-on testing. Start with the <a href="../beginners-guide/">beginner guide</a>, <a href="./spoiler-free-start/">spoiler-free start</a>, and <a href="./launch-checklist/">launch checklist</a>. Combat-specific advice belongs in the <a href="../combat-guide/">combat hub</a>; database pages will expand only when names, locations, and rewards are verified.</p><h2>After Launch</h2><p>Every route guide will show its game version, spoiler level, prerequisites, and last-tested date. Major patches will trigger targeted retests rather than silent copy changes. Pages without enough evidence remain out of the sitemap, preserving crawl budget for guides that answer a real player task.</p>`,
  "guides/launch-checklist/index.html": `<h2>Release Facts to Recheck</h2><p>Phantom Blade Zero is currently scheduled for October 29, 2026 on PS5, while Steam displays October 28 because of the global UTC unlock. Confirm the storefront countdown in your region rather than assuming a local midnight release. Download size, preload, day-one patch, editions, price, and review embargo remain time-sensitive.</p><h2>First Evidence Capture</h2><p>Save the version number, platform, default difficulty, controls, accessibility settings, and tutorial terminology before changing options. For every discovered weapon or Phantom Edge, record the exact name and acquisition source. This creates reliable guide inputs and prevents placeholder terms from becoming permanent database errors.</p>`,
  "guides/spoiler-free-start/index.html": `<h2>Confirmed Story Boundary</h2><p>The public premise says Soul was framed for killing The Order's patriarch, survived through a temporary cure, and has 66 days to uncover the conspiracy. This guide treats those marketing facts as the spoiler-free baseline and will not reveal later identities, betrayals, bosses, regions, or endings.</p><h2>Safe Navigation</h2><p>Follow settings, controls, basic defense, and weapon-system pages first. Character, quest, ending, and boss pages may contain names visible in headings, so use their spoiler labels. The release version of this route will stop before the first major irreversible choice and provide a separate warning before any missable content discussion.</p>`,
  "lore/factions/index.html": `<h2>Verified Relationship</h2><p>S-GAME identifies Soul as an elite assassin serving The Order. He is framed for murdering the organization's patriarch and hunted by former comrades while trying to find the conspiracy's mastermind. That establishes affiliation, accusation, and conflict; it does not yet verify every rank, member, allied group, or ending outcome.</p><h2>Editorial Boundary</h2><p>New faction pages require an official name or a clear in-game label. Trailer costumes, symbols, or enemy groupings are not enough on their own. After launch, entries will cite dialogue, codex text, quests, or item descriptions and will separate what Soul knows at each story stage from late-game spoilers.</p>`,
  "lore/kungfupunk/index.html": `<h2>S-GAME's Definition</h2><p>Founder Soulframe Liang describes the Phantom World as a meeting point for Chinese kungfu, intricate steampunk-like machinery, occult arts, and elements that do not fit a single category. He calls the art direction “Kungfupunk”: evolving pop-culture kungfu with punk spirit and stylish visuals. The Steam page adds inspiration from the Golden Age of Hong Kong action films.</p><h2>What It Is Not</h2><p>Kungfupunk is the developer's world and art-direction label, not a promise that every location has the same technology or that the game follows one historical period. Use it to understand the blend of martial arts, machinery, dark fantasy, and cinematic choreography—not as a substitute for verified lore.</p>`,
  "lore/phantom-world/index.html": `<h2>Official World Description</h2><p>S-GAME says the Phantom World brings together kungfu, machinery, occult arts, and stranger powers. The Steam description mentions shifting realities, echoes of memories, augmentation, higher beings, rumors, and a wider mystery. The 2023 developer post describes a semi-open structure made from multiple handcrafted maps of reasonable size rather than one continuous open world.</p><h2>What Remains Unknown</h2><p>Final region names, travel rules, map completion, backtracking limits, weather behavior, and collectible counts have not been fully published. This hub will add a region only after an official label or retail map confirms it, then connect that region to its routes, bosses, quests, items, and lore.</p>`,
  "lore/the-order/index.html": `<h2>Confirmed Story Role</h2><p>The 2023 PlayStation Blog introduction says Soul is an elite assassin serving an elusive, powerful organization called The Order. He is framed for murdering its patriarch, badly injured in the resulting hunt, and left with a temporary cure that lasts 66 days. Former comrades pursue him while he searches for the mastermind.</p><h2>Details Still Protected</h2><p>Public sources do not yet provide a complete hierarchy, member list, base locations, internal doctrine, or all possible loyalties. Those details will not be inferred from costume design alone. After launch, the page will separate early-game knowledge from spoiler sections covering leadership, quests, bosses, and ending consequences.</p>`,
  "story/index.html": `<h2>Confirmed Premise</h2><p>Soul is framed for the murder of The Order's patriarch and left with a ruined heart. A mystic healer's temporary cure gives him 66 days to find the mastermind while assassins and former comrades hunt him. Official descriptions also frame the journey around shifting loyalties, love, hate, mercy, vengeance, and a larger conspiracy.</p><h2>Spoiler Policy</h2><p>This hub covers only the public setup. Chapter names, major identities, betrayals, boss outcomes, and endings will be placed behind clear warnings after release. The <a href="./spoiler-free-story/">spoiler-free story page</a> will remain safe for new players, while detailed quest and ending routes will cite the tested game version.</p>`,
  "story/spoiler-free-story/index.html": `<h2>Safe Public Setup</h2><p>The official premise establishes four facts: Soul served The Order, he was framed for killing its patriarch, a temporary cure leaves him 66 days, and he must uncover the conspiracy while being hunted. The Steam description adds themes of shifting loyalties and a search for what it means to have a heart.</p><h2>What This Page Will Never Reveal</h2><p>Future updates will avoid hidden identities, faction turns, boss names, region reveals, quest solutions, and ending requirements. If a basic gameplay route requires mentioning a story event, the guide will warn first and use the earliest possible wording. Readers who want full context can deliberately move to the main story and ending hubs.</p>`,
  "demo/index.html": `<h2>Current Answer</h2><p>No downloadable public PS5 or Steam demo is listed on the official storefronts as of July 17, 2026. Earlier hands-on builds shown at events do not automatically mean a home demo will be released. S-GAME or the platform holders could announce one later, so this page tracks store availability rather than rumor.</p><h2>How Availability Will Be Verified</h2><p>A real public demo update requires an official store button or publisher announcement, supported regions, platforms, download size, end date if temporary, and whether progress transfers. Event-only booths, creator captures, and press previews will remain labeled as preview builds. Check the <a href="../questions/does-phantom-blade-zero-have-demo/">direct demo answer</a> for the latest status.</p>`,
  "platforms/console-vs-pc/index.html": `<h2>Confirmed Platform Baseline</h2><p>Official listings confirm PS5 and Windows PC via Steam. The PS5 page advertises DualSense vibration, trigger effects, and Game Help; Steam currently lists only Windows 10/11 64-bit in its incomplete requirements section. Final PC CPU, GPU, memory, storage, graphics presets, ultrawide support, and performance targets are still pending.</p><h2>Decision Before Benchmarks</h2><p>Choose PS5 if the confirmed controller and Game Help features matter and you prefer a fixed console target. Choose PC only if your hardware and preferred features can be checked against the final requirements. Avoid performance claims until independent retail benchmarks use the same patch and comparable settings.</p>`,
  "sources/index.html": `<h2>Current Primary References</h2><p>The editorial baseline uses the official PlayStation store for date and PS5 features, the official Steam page for PC availability, weapon counts, Phantom Edges, story, and technology, and S-GAME's PlayStation Blog introduction for The Order, the semi-open world, Kungfupunk, and combat direction. A 2024 PlayStation hands-on report supports the public block, parry, and dodge descriptions.</p><h2>Freshness and Corrections</h2><p>Time-sensitive pages show a checked date. If two official listings disagree, the page describes the difference instead of silently choosing one. Retail testing must record platform and patch; community reports can suggest a test but do not replace reproducible evidence. Corrections should update affected internal links and sitemap dates in the same deployment.</p>`,
  "updates/index.html": `<h2>What Counts as an Update</h2><p>Tracked changes include official release timing, platform listings, editions, demos, requirements, feature confirmations, trailers, State of Play details, and post-launch patches. Rumors and unsourced screenshots are not added to the timeline as facts. A changed storefront is dated and linked so readers can distinguish a new announcement from an editorial rewrite.</p><h2>Current Watch Item</h2><p>PlayStation announced a dedicated Phantom Blade Zero State of Play for later in summer 2026. When it airs, this site will compare every revealed mechanic and story term against existing pages, update confirmed answers, keep unknowns labeled, regenerate sitemaps, and record the change in the SEO changelog.</p>`,
  "updates/release-date-change/index.html": `<h2>Current Official Timing</h2><p>PlayStation lists October 29, 2026 at 02:00 UTC. Steam shows October 28, 2026, which is consistent with the same global moment appearing on the previous calendar date in some time zones. This is a storefront display difference, not evidence of two separate launches.</p><h2>How a Real Date Change Is Confirmed</h2><p>The page will update only when S-GAME, PlayStation, or Steam changes the published timing. A countdown glitch, retailer placeholder, or social rumor is not enough. If the date moves, the release hub, time-zone table, homepage, FAQ, schema, sitemap lastmod values, and GSC priority URLs should be refreshed together.</p>`,
};

const shortStatus = {
  "questions/are-there-multiple-endings/index.html": `<h2>What Is Actually Confirmed</h2><p>The official store descriptions focus on Soul's conspiracy and 66-day deadline but do not currently promise a specific number of endings. Steam user tags are community-generated and are not sufficient evidence for an ending count. The retail guide will verify ending achievements, branching choices, save behavior, and New Game Plus interaction before publishing a route.</p>`,
  "questions/can-you-change-difficulty/index.html": `<h2>Why the Answer Is Pending</h2><p>Official store pages do not currently list selectable difficulty names or whether they can be changed after starting. Event demos may use settings that differ from retail. At launch, this page will test menu availability, mid-game switching, trophy or achievement effects, accessibility assists, and whether boss behavior or rewards change.</p>`,
  "questions/does-phantom-blade-zero-have-difficulty-options/index.html": `<h2>Verification Checklist</h2><p>No final difficulty menu has been detailed on the official PlayStation or Steam pages. The release build must confirm mode names, unlock conditions, whether settings can change mid-run, and any trophy, achievement, reward, or New Game Plus restrictions. Until then, descriptions based on demos remain provisional.</p>`,
  "questions/does-phantom-blade-zero-have-new-game-plus/index.html": `<h2>Current Evidence</h2><p>S-GAME has not confirmed New Game Plus on the official store pages. A complete answer requires finishing the retail build and checking whether weapons, Phantom Edges, upgrades, quests, collectibles, difficulty, and ending progress carry over. This page will not treat genre convention as confirmation.</p>`,
  "questions/does-phantom-blade-zero-have-photo-mode/index.html": `<h2>Current Evidence</h2><p>No photo mode is advertised on the official PlayStation or Steam listings. That does not prove the feature is absent from the final menus or a later update. Launch verification will check camera controls, filters, hiding the HUD, combat restrictions, resolution, and platform differences.</p>`,
  "questions/does-phantom-blade-zero-support-controller/index.html": `<h2>Confirmed Controller Support</h2><p>The PS5 version necessarily supports the DualSense controller, and its official page specifically lists vibration and trigger effects. Steam controller details have not yet been fully published. PC testing will verify wired and wireless DualSense behavior, Xbox-style pads, button prompts, remapping, haptics, and fallback input.</p>`,
  "questions/how-long-is-phantom-blade-zero/index.html": `<h2>Why 66 Days Is Not a Length Estimate</h2><p>Soul's 66-day deadline is part of the official story premise, not a confirmed real-time campaign timer or hour count. S-GAME has not published main-story, completionist, or speedrun estimates. Reliable figures require multiple completed retail playthroughs with route, difficulty, exploration, and cutscene choices recorded.</p>`,
  "search/index.html": `<h2>Browse by Verified Need</h2><p>Use the question hub for direct platform and feature answers, combat for tested mechanics, story and lore for spoiler-labeled context, and databases for named equipment after release. Pages held outside the sitemap are planning inventory, not finished guides. If a result conflicts with the current game version, report the platform, patch, and page URL so it can be retested.</p>`,
  "trailers/index.html": `<h2>Trailer Evidence Policy</h2><p>Official trailers can confirm that a character, weapon, location, or animation was publicly shown, but edited footage cannot by itself prove an unlock method, final name, input, damage value, or launch feature. Each entry will record the publisher, publication date, video title, and what is directly visible. Retail guides take precedence when showcase content changes.</p>`,
};

for (const [relative, addition] of Object.entries({ ...additions, ...shortStatus })) {
  const file = path.join(root, relative);
  const html = await readFile(file, "utf8");
  if (html.includes("data-round3=\"expanded\"")) continue;
  const marker = `<div data-round3="expanded">${addition}</div>`;
  if (!html.includes("</article>")) throw new Error(`No article in ${relative}`);
  await writeFile(file, html.replace("</article>", `${marker}</article>`));
}

function questionPage({ slug, title, description, answer, schemaAnswer, body, related }) {
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8" /><meta name="viewport" content="width=device-width, initial-scale=1" /><title>${title}</title><meta name="description" content="${description}" /><link rel="canonical" href="https://phantombladezerowiki.wiki/questions/${slug}/" /><link rel="stylesheet" href="../../styles.css" /><script type="application/ld+json">${JSON.stringify({ "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [{ "@type": "Question", name: title.replace(/ \|.*$/, ""), acceptedAnswer: { "@type": "Answer", text: schemaAnswer } }] })}</script></head>
<body><header class="site-header"><a class="brand" href="../../"><span class="brand-mark">PBZ</span><span>Phantom Blade Zero Wiki</span></a><nav class="nav"><a href="../">Questions</a><a href="../../weapons/">Weapons</a><a href="../../lore/kungfupunk/">Lore</a><a href="../../sources/">Sources</a></nav></header><main><section class="page-hero"><p class="eyebrow">Official-source answer · checked July 17, 2026</p><h1>${title.replace(/ \|.*$/, "")}</h1><p>${answer}</p></section><section class="section content-grid"><article class="article-body">${body}<h2>Source and Update Rule</h2><p>This answer is based on the <a href="${officialSteam}">official Steam description</a>${slug.includes("rainblood") ? ` and <a href="${officialBlog}">S-GAME's PlayStation Blog introduction</a>` : ""}. It will be updated if the retail build or an official announcement changes the wording.</p></article><aside class="toc"><h2>Related</h2>${related.map(([href, label]) => `<a href="${href}">${label}</a>`).join("")}</aside></section></main><footer class="footer"><p>Unofficial fan guide using primary sources.</p><a href="../../">Home</a></footer></body></html>\n`;
}

const newQuestions = [
  { slug: "can-you-get-enemy-weapons", title: "Can You Get Enemy Weapons in Phantom Blade Zero?", description: "Yes. The official Phantom Blade Zero Steam page says powerful foes can drop weapons. Learn what is confirmed and what still needs launch testing.", answer: "<strong>Yes.</strong> The official Steam description says defeating powerful foes lets Soul obtain their weapons.", schemaAnswer: "Yes. The official Steam description says players can defeat powerful foes to obtain their weapons. Exact drop rules and the full list still require launch verification.", body: `<h2>What Is Confirmed</h2><p>S-GAME presents enemy weapon acquisition as part of arsenal growth. The same listing promises more than 30 weapons and more than 20 Phantom Edges, although it does not say that every enemy weapon is obtainable or that all drops are random.</p><h2>What Still Needs Testing</h2><p>The retail build must confirm which foes award weapons, whether rewards are guaranteed, how difficulty affects acquisition, whether missed drops can be recovered, and how upgrades or duplicates work. Boss and weapon pages will link the exact source only after it is reproduced.</p>`, related: [["../../weapons/", "Weapon Hub"], ["../how-many-weapons-in-phantom-blade-zero/", "How Many Weapons?"], ["../can-you-use-enemy-signature-techniques/", "Enemy Techniques"]] },
  { slug: "can-you-use-enemy-signature-techniques", title: "Can You Use Enemy Signature Techniques in Phantom Blade Zero?", description: "The official Steam page says obtained enemy weapons include their signature techniques. See what this confirms and what remains unknown before launch.", answer: "<strong>Yes, for obtainable enemy weapons.</strong> S-GAME says defeating powerful foes grants their weapons and signature techniques.", schemaAnswer: "Yes. S-GAME says powerful foes can yield their weapons and signature techniques, although the exact enemies, inputs, and progression rules are not yet fully published.", body: `<h2>How the Official Description Frames It</h2><p>The feature connects enemy victories to a growing combat arsenal: obtain a powerful foe's weapon and gain its signature technique. That supports build variety, but does not confirm that every boss or ordinary enemy contributes a unique move.</p><h2>Launch Questions</h2><p>The wiki will test whether techniques are tied permanently to a weapon, require upgrades, consume a resource, can be mixed with other weapons, or change by difficulty. Each verified entry will show acquisition source, input, cost, role, and a short practical use case.</p>`, related: [["../can-you-get-enemy-weapons/", "Enemy Weapons"], ["../../weapons/", "Weapons"], ["../../combat-guide/", "Combat Guide"]] },
  { slug: "is-phantom-blade-zero-inspired-by-hong-kong-action-movies", title: "Is Phantom Blade Zero Inspired by Hong Kong Action Movies?", description: "Yes. S-GAME cites the Golden Age of Hong Kong action films and martial-arts choreography as major Phantom Blade Zero inspirations.", answer: "<strong>Yes.</strong> The official Steam page explicitly cites the Golden Age of Hong Kong action films as an inspiration.", schemaAnswer: "Yes. S-GAME says Phantom Blade Zero is inspired by the Golden Age of Hong Kong action films and uses martial-arts choreography and motion-capture technology to shape its combat presentation.", body: `<h2>How the Inspiration Appears</h2><p>S-GAME connects the influence to fast steel-on-steel action, martial arts, machinery, and its Kungfupunk identity. The Steam description also says Unreal Engine 5 and motion capture help translate authentic techniques and film choreography into modern game design.</p><h2>What the Claim Does Not Mean</h2><p>Inspiration is not proof that every move reproduces a specific film scene or that the game's world is historically literal. Phantom Blade Zero combines wuxia, dark fantasy, machinery, occult elements, and its own fictional setting. The best comparison is artistic and choreographic, not a claim of direct adaptation.</p>`, related: [["../../lore/kungfupunk/", "Kungfupunk"], ["../what-engine-does-phantom-blade-zero-use/", "Unreal Engine 5"], ["../../combat-guide/", "Combat"]] },
  { slug: "is-phantom-blade-zero-related-to-rainblood", title: "Is Phantom Blade Zero Related to Rainblood?", description: "Yes. S-GAME founder Soulframe Liang calls Phantom Blade Zero the spiritual rebirth of the original Rainblood. Learn what that relationship means.", answer: "<strong>Yes.</strong> S-GAME calls Phantom Blade Zero the “spiritual rebirth” of the original Rainblood, not a simple remake announcement.", schemaAnswer: "Yes. S-GAME founder Soulframe Liang describes Phantom Blade Zero as the spiritual rebirth of the original Rainblood, expanding the core into a much larger Unreal Engine 5 game.", body: `<h2>From Rainblood to Phantom Blade</h2><p>Liang says the project began with the 2010 RPG Maker title Rainblood: Town of Death. Rainblood grew into the Phantom Blade franchise, much of which appeared on mobile and did not launch outside China. Phantom Blade Zero is presented as a much larger global project built in Unreal Engine 5.</p><h2>Spiritual Rebirth, Not a Continuity Shortcut</h2><p>The phrase confirms creative lineage, but it does not by itself establish which earlier plot events, characters, or endings remain canon. New players should not assume prior games are required homework. Continuity details will be labeled only when the retail game or S-GAME explains them directly.</p>`, related: [["../../story/", "Story"], ["../../lore/phantom-world/", "Phantom World"], ["../who-made-phantom-blade-zero/", "Developer"]] },
];

for (const page of newQuestions) {
  const directory = path.join(root, "questions", page.slug);
  await mkdir(directory, { recursive: true });
  await writeFile(path.join(directory, "index.html"), questionPage(page));
}

const hubFile = path.join(root, "questions/index.html");
let hub = await readFile(hubFile, "utf8");
const combatNeedle = `<a class="mini-card" href="./does-phantom-blade-zero-have-character-creation/"><strong>Character creation?</strong>Fixed protagonist versus customization.</a>`;
if (!hub.includes("./can-you-get-enemy-weapons/")) {
  hub = hub.replace(combatNeedle, `${combatNeedle}<a class="mini-card" href="./can-you-get-enemy-weapons/"><strong>Enemy weapons?</strong>Confirmed acquisition from powerful foes.</a><a class="mini-card" href="./can-you-use-enemy-signature-techniques/"><strong>Enemy techniques?</strong>Signature techniques explained.</a>`);
}
const loreNeedle = `<a class="mini-card" href="./who-made-phantom-blade-zero/"><strong>Who made the game?</strong>Developer, publisher, and technology.</a>`;
if (!hub.includes("./is-phantom-blade-zero-related-to-rainblood/")) {
  hub = hub.replace(loreNeedle, `${loreNeedle}<a class="mini-card" href="./is-phantom-blade-zero-inspired-by-hong-kong-action-movies/"><strong>Hong Kong film inspiration?</strong>Official choreography influence.</a><a class="mini-card" href="./is-phantom-blade-zero-related-to-rainblood/"><strong>Related to Rainblood?</strong>The franchise lineage.</a>`);
}
await writeFile(hubFile, hub);

console.log(`Expanded ${Object.keys(additions).length + Object.keys(shortStatus).length} pages and added ${newQuestions.length} question URLs.`);
